name: Unit Test
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "src/**"
      - "packages/**"
      - "apps/**"
      - "public/**"
      - ".github/workflows/**"
      - "package.json"
      - "vite.config.ts"
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Test
        run: bun run test
